## Running the PBE Tool using the JSON File

### Old Version of the PBE Application IGNORE

In [ ]:
# # JSON_INPUT_FILE = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\tmp.SimCenter\\templatedir\\for_SP3_Inputs.json"
# #"C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\CEE288_starter_2025\2475\RSN548_CHALFANT.A_A-BEN270.AT2"

# JSON_INPUT_FILE = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\tmp.SimCenter\\templatedir\\CS229_SDOF_Old_App.json"
# PYTHON_EXE = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\PBE_Windows_Download_old\\PBE_Windows_Download\\applications\\python\\python.exe"
# PBE_WORKFLOW_SCRIPT = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\PBE_Windows_Download_old\\PBE_Windows_Download\\applications\\Workflow\\sWHALE.py"
# PBE_APP_WORKFLOW = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\PBE_Windows_Download_old\\PBE_Windows_Download\\applications\\Workflow\\WorkflowApplications.json"

In [ ]:
# !"{PYTHON_EXE}" "{PBE_WORKFLOW_SCRIPT}" runningLocal "{JSON_INPUT_FILE}" "{PBE_APP_WORKFLOW}"

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-24T09:33:22
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
09:33:22 Started running the workflow script
         -----------------------------------------------------------------------
09:33:22 Inputs provided:
         workflow input file: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\tmp.SimCenter\templatedir\CS229_SDOF_Old_App.json
         application registry file: C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
09:33:22 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
09:33:22 Parsing workflow input file
         Loading the json file...
           OK
         No units specified; using Standard units.
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: CS229_SDOF_Old_App.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\tmp.SimCenter
         Local applications dir : C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download
         Remote applications dir : C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
09:33:22 Running the workflow script
         -----------------------------------------------------------------------
09:33:22 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
09:33:22 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

ERROR Parsing PEER Record:check format of file: RSN548_CHALFANT.A_A-BEN270.AT2eventTimeSeriesObj wrong
eventTimeSeries wrong
eventFactor wrong
populatedTimeSeriesObj wrong
populatedTimeSeries wrong
populatedFactor wrong
pFactor = 0


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download_old\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

         -----------------------------------------------------------------------
09:33:22  ERROR
09:33:22 return code: 4294967295
         -----------------------------------------------------------------------
Analysis Failed at EDP
         =====================================
ERROR no patterns with Seismic event

### New Version of the PBE Application IGNORE

In [ ]:
# JSON_INPUT_FILE = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\tmp.SimCenter\\templatedir\\CS229_SDOF_New_App.json"
# PYTHON_EXE = "C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\PBE_Windows_Download\\applications\\python\\python.exe"
# PBE_WORKFLOW_SCRIPT = "C:/Users/varun/OneDrive - Stanford/Desktop/PBE_Windows_Download/applications/Workflow/sWHALE.py"
# PBE_APP_WORKFLOW = "C:/Users/varun/OneDrive - Stanford/Desktop/PBE_Windows_Download/applications/Workflow/WorkflowApplications.json"

In [ ]:
# !"{PYTHON_EXE}" "{PBE_WORKFLOW_SCRIPT}" runningLocal "{JSON_INPUT_FILE}" "{PBE_APP_WORKFLOW}"

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-18T00:23:29
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
00:23:29 Started running the workflow script
         -----------------------------------------------------------------------
00:23:29 Inputs provided:
         workflow input file: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\tmp.SimCenter\templatedir\CS229_SDOF_New_App.json
         application registry file: C:/Users/varun/OneDrive - Stanford/Desktop/PBE_Windows_Download/applications/Workflow/WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
00:23:29 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
00:23:29 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: CS229_SDOF_New_App.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\tmp.SimCenter
         Local applications dir : C:/Users/varun/OneDrive - Stanford/Desktop/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
00:23:29 Running the workflow script
         -----------------------------------------------------------------------
00:23:29 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
00:23:29 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

ERROR Parsing PEER Record:check format of file: RSN548_CHALFANT.A_A-BEN270.AT2eventTimeSeriesObj wrong
eventTimeSeries wrong
eventFactor wrong
populatedTimeSeriesObj wrong
populatedTimeSeries wrong
populatedFactor wrong
pFactor = 0


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

         -----------------------------------------------------------------------
00:23:29  ERROR
00:23:29 return code: 4294967295
         -----------------------------------------------------------------------
Analysis Failed at EDP
         =====================================
ERROR no patterns with Seismic event

C:\Users\varun\OneDrive - Stanford\Desktop\PBE_Windows_Download\applications\Workflow\whale\main.py:72: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources

### Getting the Saved Building Inventory and Ground Motion Records

In [ ]:
#Import the pkl files in data folder
import pickle
from pathlib import Path

# Going to the folder where the Project is stored
notebook_dir = Path(r'G:\Shared drives\\CS229 Project')

# Going to the data folder inside the Project folder
with open(notebook_dir / 'Code/data/filtered_buildings_Complete_with_unique_id.pkl', 'rb') as f:
    buildings_data = pickle.load(f)

print(f"Loaded {len(buildings_data)} buildings from complete data")

FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Shared drives\\\\CS229 Project/Code/data/filtered_buildings_Complete_with_unique_id.pkl'

In [ ]:
# #create a unique ID for each building the tag should have constype, occupancy and a serial number to make it unique in buildings_data dataframe
# buildings_data['unique_id'] = buildings_data.apply(lambda row: f"{row['constype']}_{row['occupancy']}_{row.name}", axis=1)
# buildings_data.columns

,id,buildingheight,erabuilt,numstories,footprintArea,lon,lat,fparea,repaircost,constype,occupancy,fd_id,found_ht,ground_elv,geometry,unique_id
0,30,29,1967.0,1,9449.0,-117.662404,33.503555,9469.5000,1628726.060,C1,COM4,477051287.0,0.5,125.264162,"POLYGON ((-117.66258 33.50378, -117.66246 33.5...",C1_COM4_0
1,31,30.800000000000001,1967.0,1,11196.0,-117.663316,33.503757,15480.0000,2515049.750,W1,COM4,477051289.0,0.5,122.362539,"POLYGON ((-117.66359 33.50382, -117.66355 33.5...",W1_COM4_1
2,32,25.600000000000001,1986.0,1,129025.0,-117.676660,33.554962,1355.4945,293869.128,C1,COM3,474243901.0,0.5,276.490969,"POLYGON ((-117.67614 33.55443, -117.67614 33.5...",C1_COM3_2
3,35,22.199999999999999,1985.0,2,40255.0,-117.663614,33.492689,71740.6121,8787414.350,S1,COM1,474245528.0,0.5,77.116917,"POLYGON ((-117.66327 33.49292, -117.66327 33.4...",S1_COM1_3
4,41,15.300000000000001,1986.0,2,4316.0,-117.673213,33.585088,6296.0000,1322281.380,RM1,COM8,474247317.0,0.5,331.733619,"POLYGON ((-117.67333 33.58519, -117.67322 33.5...",RM1_COM8_4

In [ ]:
# #Import the pkl files in data folder
# import pickle
# from pathlib import Path

# # Get the directory where the notebook is located
# notebook_dir = Path(r'G:\Shared drives\\CS229 Project')

# #Save buildings_data to a new pkl file
# with open(notebook_dir / 'Code/data/filtered_buildings_Complete_with_unique_id.pkl', 'wb') as f:
#     pickle.dump(buildings_data, f)

# print("Saved buildings_data with unique IDs to filtered_buildings_Complete_with_unique_id.pkl")

In [ ]:
## create a subset for the building inventory having the first 5 buildings only
buildings_data_subset = buildings_data.head(1)
buildings_data_subset.head(5)

,id,buildingheight,erabuilt,numstories,footprintArea,lon,lat,fparea,repaircost,constype,occupancy,fd_id,found_ht,ground_elv,geometry,unique_id
0,30,29,1967.0,1,9449.0,-117.662404,33.503555,9469.5,1628726.06,C1,COM4,477051287.0,0.5,125.264162,"POLYGON ((-117.66258 33.50378, -117.66246 33.5...",C1_COM4_0

### Make a copy of the Template scInput JSON file

In [ ]:
# make a copy of the scInput.json file with the filename having the unique_id
# using the template file for each building in buildings_data
#"G:\Shared drives\CS229 Project\Code\data\JSON_Input_files\scInput_template.json"
import json
import shutil
from pathlib import Path

# Template file path
template_file = notebook_dir / "Code/JSON_Input_files/scInput_template.json"

# Output directory for individual building JSON files
output_dir = notebook_dir / "Code/JSON_Input_files/buildings"
output_dir.mkdir(parents=True, exist_ok=True)

# Create a copy for each building with unique_id in filename
for idx, row in buildings_data_subset.iterrows(): ## RUNNING OVER BUILDING DATA SUBSET
    unique_id = row['unique_id']
    output_file = output_dir / f"scInput_{unique_id}.json"

    # Copy template
    shutil.copyfile(template_file, output_file)

    print(f"Created: {output_file.name}")

print(f"\nTotal files created: {len(buildings_data_subset)}")

Created: scInput_C1_COM4_0.json

Total files created: 1

### Make copies of the output folder template for each building simulation

In [ ]:
# Make copies of the output folder template for each building with unique_id as folder name
import shutil
from pathlib import Path

# Template folder path
template_folder = notebook_dir / "PBE_Analysis/OUTPUT_FOLDER_TEMPLATE"

# Output directory for individual building folders
output_base_dir = notebook_dir / "PBE_Analysis/buildings"
output_base_dir.mkdir(parents=True, exist_ok=True)

# Create a copy of the folder for each building with unique_id as folder name
for idx, row in buildings_data_subset.iterrows():
    unique_id = row['unique_id']
    output_folder = output_base_dir / unique_id

    # Copy entire folder structure
    if output_folder.exists():
        shutil.rmtree(output_folder)  # Remove if exists

    shutil.copytree(template_folder, output_folder)

    print(f"Created folder: {output_folder.name}")

print(f"\nTotal folders created: {len(buildings_data_subset)}")

Created folder: C1_COM4_0

Total folders created: 1

### Updating the input JSON files for each building in the Building Inventory Subset

In [ ]:
# # update the JSON input file to have only the buildings in buildings_data_subset
# import json
# from sympy import sec
# # for the input file created for the first building in buildings_data_subset later convert this to a loop for all buildings
# JSON_INPUT_FILE = output_dir / f"scInput_{buildings_data_subset['unique_id'][0]}.json"
# with open(JSON_INPUT_FILE, 'r') as f:
#     json_data = json.load(f)
# # Update the building inventory path in the JSON data
# json_data['DL']['buildingInventoryFile'] = "C:/Users/varun/OneDrive - Stanford/Desktop/Stanford/5. Autumn 25 Quarter/Independent Study CEE299/PBE_Analysis/From_GUI/tmp.SimCenter/templatedir/CMP_QNT.csv" #TODO NEED TO UPDATE EXCEL BEFORE EACH RUN,  Path to the CMP_QNT file in the OUTPUT_FOLDER
# json_data['DL']["NumberofStories"] = buildings_data_subset['numstories'][0]
# json_data['DL']["OccupancyType"] = buildings_data_subset['occupancy'][0]
# json_data['DL']["PlanArea"] = buildings_data_subset['fparea'][0] #footprintArea seems to have weird values, using fpArea instead (NSI?)
# json_data["DL"]["Demands"]["SampleSize"] = "1000" #Earlier 10000 was giving 30s of run time per building, so reduced to 1000 for testing, should be fine
# json_data["Events"]["Records"]["fileName"]= "RSN1714_NORTH392_W70000.AT2" #TODO: Update this to the path of the ground motion file names in the new column
# json_data["Events"]["Records"]["filePath"]= "C:/Users/varun/Downloads" #TODO: Update this to the path of the ground motion folder
# json_data["Events"]["name"] = "1714" #TODO Update this based on the column providing RSN number
# json_data["GeneralInformation"]["DesignLevel"] = "High-Code" #Set to high for now TODO: change to middle/mid? check PBE Tool

# # Note : "units": {"force": "kips","length": "ft","temperature": "C","time": "sec"}
# json_data["GeneralInformation"]["NumberOfStories"] = buildings_data_subset['numstories'][0]
# json_data["GeneralInformation"]["PlanArea"] = buildings_data_subset['fparea'][0]
# json_data["GeneralInformation"]["StructureType"] = buildings_data_subset['constype'][0]
# json_data["GeneralInformation"]["name"] = buildings_data_subset['unique_id'][0]
# json_data["GeneralInformation"]["yearBuilt"] = buildings_data_subset['erabuilt'][0]
# json_data["GeneralInformation"]["height"] = buildings_data_subset['buildingheight'][0]
# json_data["GeneralInformation"]["width"] = (buildings_data_subset['fparea'][0]/buildings_data_subset['numstories'][0])**0.5 #Assuming square footprint for now
# json_data["GeneralInformation"]["depth"] = (buildings_data_subset['fparea'][0]/buildings_data_subset['numstories'][0])**0.5 #Assuming square footprint for now
# json_data["GeneralInformation"]["location"]["latitude"] = buildings_data_subset['lat'][0]
# json_data["GeneralInformation"]["location"]["longitude"] = buildings_data_subset['lon'][0]
# json_data["GeneralInformation"]["stories"] = buildings_data_subset['numstories'][0]
# json_data["GeneralInformation"]["planArea"] = buildings_data_subset['fparea'][0]


# ### SHOULD BE DIFFERENT FOR EACH PERSON !!!
# json_data["localAppDir"] = "C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download"
# json_data["remoteAppDir"] = "C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download"
# json_data["runDir"] = "C:/Users/varun/OneDrive - Stanford/Desktop/Stanford/5. Autumn 25 Quarter/Independent Study CEE299/PBE_Analysis/From_GUI/tmp.SimCenter"
# json_data["workingDir"] = "C:/Users/varun/OneDrive - Stanford/Desktop/Stanford/5. Autumn 25 Quarter/Independent Study CEE299/PBE_Analysis/From_GUI"

In [ ]:
# update the JSON input file to have only the buildings in buildings_data_subset
import json
from sympy import sec
# Output directory for individual building JSON files
output_dir = notebook_dir / "Code/JSON_Input_files/buildings"
# Output directory for individual building output folders
output_base_dir = notebook_dir / "PBE_Analysis/buildings"
# for the input file created for the first building in buildings_data_subset later convert this to a loop for all buildings
JSON_INPUT_FILE = output_dir / f"scInput_{buildings_data_subset['unique_id'][0]}.json"
# for the output folder created for the first building in buildings_data_subset later convert this to a loop for all buildings
OUTPUT_FOLDER = output_base_dir / f"{buildings_data_subset['unique_id'][0]}"
with open(JSON_INPUT_FILE, 'r') as f:
    json_data = json.load(f)

# Update the building inventory path in the JSON data
json_data['DL']['Asset']['ComponentAssignmentFile'] = str(OUTPUT_FOLDER / "tmp.SimCenter/templatedir/CMP_QNT.csv") #CHECK IF NEED TO UPDATE EXCEL BEFORE EACH RUN,  Path to the CMP_QNT file in the OUTPUT_FOLDER
json_data['DL']["Asset"]["NumberOfStories"] = buildings_data_subset['numstories'][0]
json_data['DL']["Asset"]["OccupancyType"] = buildings_data_subset['occupancy'][0]
json_data['DL']["Asset"]["PlanArea"] = buildings_data_subset['fparea'][0] #footprintArea seems to have weird values, using fpArea instead (NSI?)
json_data["DL"]["Demands"]["SampleSize"] = "1000" #Earlier 10000 was giving 30s of run time per building, so reduced to 1000 for testing, should be fine

# Events section corrected to proper indexing
json_data["Events"][0]["Events"][0]["Records"][0]["fileName"]= "RSN1714_NORTH392_W70000.AT2" #TODO: Update this to the path of the ground motion file names in the new column
json_data["Events"][0]["Events"][0]["Records"][0]["filePath"]= "C:/Users/varun/Downloads" #TODO: Update this to the path of the ground motion folder
json_data["Events"][0]["Events"][0]["name"] = "1714" #TODO Update this based on the column providing RSN number

json_data["GeneralInformation"]["DesignLevel"] = "High-Code" #Set to high for now TODO: change to middle/mid? check PBE Tool

# Note : "units": {"force": "kips","length": "ft","temperature": "C","time": "sec"}
json_data["GeneralInformation"]["NumberOfStories"] = buildings_data_subset['numstories'][0]
json_data["GeneralInformation"]["PlanArea"] = buildings_data_subset['fparea'][0]
json_data["GeneralInformation"]["StructureType"] = buildings_data_subset['constype'][0]
json_data["GeneralInformation"]["name"] = buildings_data_subset['unique_id'][0]
json_data["GeneralInformation"]["YearBuilt"] = buildings_data_subset['erabuilt'][0]
json_data["GeneralInformation"]["height"] = buildings_data_subset['buildingheight'][0]
json_data["GeneralInformation"]["width"] = str(float((float(buildings_data_subset['fparea'][0])/float(buildings_data_subset['numstories'][0]))**0.5)) #Assuming square footprint for now
json_data["GeneralInformation"]["depth"] = str(float((float(buildings_data_subset['fparea'][0])/float(buildings_data_subset['numstories'][0]))**0.5)) #Assuming square footprint for now
json_data["GeneralInformation"]["location"]["latitude"] = buildings_data_subset['lat'][0]
json_data["GeneralInformation"]["location"]["longitude"] = buildings_data_subset['lon'][0]
json_data["GeneralInformation"]["stories"] = buildings_data_subset['numstories'][0]
json_data["GeneralInformation"]["planArea"] = buildings_data_subset['fparea'][0]


### SHOULD BE DIFFERENT FOR EACH PERSON !!!
json_data["localAppDir"] = "C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download"
json_data["remoteAppDir"] = "C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download"

## CHECK IF DIFFERENT. SHOULD BE FINE IF notebook_dir IS RIGHT
# json_data["runDir"] = "C:/Users/varun/OneDrive - Stanford/Desktop/Stanford/5. Autumn 25 Quarter/Independent Study CEE299/PBE_Analysis/From_GUI/tmp.SimCenter"
# json_data["workingDir"] = "C:/Users/varun/OneDrive - Stanford/Desktop/Stanford/5. Autumn 25 Quarter/Independent Study CEE299/PBE_Analysis/From_GUI"
json_data["runDir"] = str(OUTPUT_FOLDER / "tmp.SimCenter")
json_data["workingDir"] = str(OUTPUT_FOLDER)

# Update the JSON file
with open(JSON_INPUT_FILE, 'w') as f:
    json.dump(json_data, f, indent=4)

### Running PBE Locally

In [ ]:
import os
import subprocess
from pathlib import Path
import shutil

# Output directory for individual building JSON files
output_dir = notebook_dir / "Code/JSON_Input_files/buildings"
# Output directory for individual building output folders
output_base_dir = notebook_dir / "PBE_Analysis/buildings"
# for the input file created for the first building in buildings_data_subset later convert this to a loop for all buildings
JSON_INPUT_FILE = output_dir / f"scInput_{buildings_data_subset['unique_id'][0]}.json"
# for the output folder created for the first building in buildings_data_subset later convert this to a loop for all buildings
OUTPUT_FOLDER = output_base_dir / f"{buildings_data_subset['unique_id'][0]}"

# Make a copy of the JSON input file
CURRENT_SCINPUT_FILE = output_dir / "scInput.json"
shutil.copy(JSON_INPUT_FILE, CURRENT_SCINPUT_FILE)
### DIFFERENT FOR EACH PERSON !!!
WORKDIR = Path(r"C:\\Users\\varun\\Downloads") # WHERE YOUR PBE FILES ARE DOWNLOADED
PYTHON_EXE = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\python\\python.exe")
PBE_WORKFLOW_SCRIPT = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\sWHALE.py")
PBE_APP_WORKFLOW = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\WorkflowApplications.json")

#Add Dakota bin folder to PATH for this run
env = os.environ.copy()
env["PATH"] = r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\dakota\\bin" + os.pathsep + env["PATH"]
cmd = [
    str(PYTHON_EXE),
    str(PBE_WORKFLOW_SCRIPT),
    "runningLocal",
    str(CURRENT_SCINPUT_FILE),
    str(PBE_APP_WORKFLOW),
]

print("Running:\n", " ".join(f'"{c}"' for c in cmd))
print("CWD:", WORKDIR)

result = subprocess.run(
    cmd,
    cwd=str(WORKDIR),
    env=env,              # important: use modified PATH
    capture_output=True,
    text=True,
)

print("=== STDOUT ===")
print(result.stdout)
print("=== STDERR ===")
print(result.stderr)
print("Return code:", result.returncode)

Running:
 "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py" "runningLocal" "G:\Shared drives\CS229 Project\Code\JSON_Input_files\buildings\scInput.json" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json"
CWD: C:\Users\varun\Downloads
=== STDOUT ===

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-12-01T11:06:19
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
11:06:20 Started running the workflow script
         -----------------------------------------------------------------------
11:06:20 Inputs provided:
         workflow input file: G:\Shared drives\CS229 Project\Code\JSON_Input_files\buildings\scInput.json
         application registry file: C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
11:06:20 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
11:06:20 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: scInput.json
           workflowOutput: EDP.json
         Run dir : G:\Shared drives\CS229 Project\PBE_Analysis\buildings\C1_COM4_0\tmp.SimCenter
         Local applications dir : C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
11:06:22 Running the workflow script
         -----------------------------------------------------------------------
11:06:22 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
11:06:23 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

file: RSN1714_NORTH392_W70000.AT2 NPTS= 749 dT= 749 0.01
eventTimeSeriesObj got
eventTimeSeries got
eventFactor got


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running Simulation app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performSIMULATION\capacitySpectrum\runCMS2.py" "--filenameAIM" "AIM.json" "--filenameSAM" "SAM.json" "--filenameEVENT" "EVENT.json" "--filenameEDP" "EDP.json" "--filenameSIM" "SIM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------
11:06:27 Creating the workflow driver file
11:06:27 driver.bat
         Workflow driver file successfully created.
         -----------------------------------------------------------------------
         Gathering Workflow Inputs.
Output:

RANDOM VARIABLES: numORIG: 1 new: 1
RANDOM VARIABLES: numORIG: 0 new: 1
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in AIM.json.sc AIM.json
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in EVENT.json.sc EVENT.json


         Successfully Gathered Inputs.
         -----------------------------------------------------------------------
11:06:28 Running response simulation
         Simulation command:

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performUQ\dakota\DakotaUQ.py" "--workflowInput" "G:\Shared drives\CS229 Project\PBE_Analysis\buildings\C1_COM4_0\tmp.SimCenter\templatedir/sc_scInput.json" "--driverFile" "sc_driver" "--workflowOutput" "EDP.json" "--runType" "runningLocal"

Output:

cwd: G:\Shared drives\CS229 Project\PBE_Analysis\buildings\C1_COM4_0\tmp.SimCenter\templatedir
EVAL CONCURRENCY: 12
NEW ORDER:
 size: 1
1 0
Running Dakota:  dakota -input dakota.in -output dakota.out -error dakota.err


         -----------------------------------------------------------------------
11:06:36 Running damage and loss assessment
         Damage and loss assessment command (2):

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performDL\pelicun3\pelicun3_wrapper.py" "--filenameDL" "AIM.json" "--demandFile" "response.csv" "--dirnameOutput" "G:\Shared drives\CS229 Project\PBE_Analysis\buildings\C1_COM4_0\tmp.SimCenter"

         2025-12-01T19:06:42Z Initializing pelicun calculation.

                  The loss model does not provide loss information for the following component(s) in the asset model: [('NSA.EDU2', 'Time'), ('NSD.EDU2', 'Time')].

         2025-12-01T19:06:55Z pelicun calculation completed.

         Damage and loss assessment finished successfully.
         -----------------------------------------------------------------------
11:06:56 No performance assessment requested, performance assessment step is skipped.
         -----------------------------------------------------------------------
11:06:56 Workflow completed.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

=== STDERR ===

Return code: 0

In [ ]:
# import os
# import subprocess
# from pathlib import Path

# WORKDIR = Path(r"C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\Code")
# JSON_INPUT_FILE = WORKDIR / "scInput_edited.json"

# PYTHON_EXE = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\python\\python.exe")
# PBE_WORKFLOW_SCRIPT = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\sWHALE.py")
# PBE_APP_WORKFLOW = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\WorkflowApplications.json")

# #Add Dakota bin folder to PATH for this run
# env = os.environ.copy()
# env["PATH"] = r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\dakota\\bin" + os.pathsep + env["PATH"]
# cmd = [
#     str(PYTHON_EXE),
#     str(PBE_WORKFLOW_SCRIPT),
#     "runningLocal",
#     str(JSON_INPUT_FILE),
#     str(PBE_APP_WORKFLOW),
# ]

# print("Running:\n", " ".join(f'"{c}"' for c in cmd))
# print("CWD:", WORKDIR)

# result = subprocess.run(
#     cmd,
#     cwd=str(WORKDIR),
#     env=env,              # important: use modified PATH
#     capture_output=True,
#     text=True,
# )

# print("=== STDOUT ===")
# print(result.stdout)
# print("=== STDERR ===")
# print(result.stderr)
# print("Return code:", result.returncode)

Running:
 "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py" "runningLocal" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\Code\scInput_edited.json" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json"
CWD: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\Code
=== STDOUT ===

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-28T13:48:08
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:48:08 Started running the workflow script
         -----------------------------------------------------------------------
13:48:08 Inputs provided:
         workflow input file: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\Code\scInput_edited.json
         application registry file: C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
13:48:08 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
13:48:08 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: scInput_edited.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter
         Local applications dir : C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:48:08 Running the workflow script
         -----------------------------------------------------------------------
13:48:08 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
13:48:08 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

file: RSN1714_NORTH392_W70000.AT2 NPTS= 749 dT= 749 0.01
eventTimeSeriesObj got
eventTimeSeries got
eventFactor got


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running Simulation app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performSIMULATION\capacitySpectrum\runCMS2.py" "--filenameAIM" "AIM.json" "--filenameSAM" "SAM.json" "--filenameEVENT" "EVENT.json" "--filenameEDP" "EDP.json" "--filenameSIM" "SIM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------
13:48:10 Creating the workflow driver file
13:48:10 driver.bat
         Workflow driver file successfully created.
         -----------------------------------------------------------------------
         Gathering Workflow Inputs.
Output:

RANDOM VARIABLES: numORIG: 1 new: 1
RANDOM VARIABLES: numORIG: 0 new: 1
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in AIM.json.sc AIM.json
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in EVENT.json.sc EVENT.json


         Successfully Gathered Inputs.
         -----------------------------------------------------------------------
13:48:10 Running response simulation
         Simulation command:

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performUQ\dakota\DakotaUQ.py" "--workflowInput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter\templatedir/sc_scInput_edited.json" "--driverFile" "sc_driver" "--workflowOutput" "EDP.json" "--runType" "runningLocal"

Output:

cwd: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter\templatedir
EVAL CONCURRENCY: 12
NEW ORDER:
 size: 1
1 0
Running Dakota:  dakota -input dakota.in -output dakota.out -error dakota.err


         -----------------------------------------------------------------------
13:48:16 Running damage and loss assessment

=== STDERR ===
Traceback (most recent call last):
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 272, in <module>
    main(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 204, in main
    runSWhale(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 121, in runSWhale
    WF.estimate_losses(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\whale\main.py", line 2704, in estimate_losses
    shutil.copy(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\PBE_Analysis\\From_GUI\\tmp.SimCenter\\templatedir\\scInput_edited.json'

Return code: 1
=== STDOUT ===

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-28T13:48:08
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:48:08 Started running the workflow script
         -----------------------------------------------------------------------
13:48:08 Inputs provided:
         workflow input file: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\Code\scInput_edited.json
         application registry file: C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
13:48:08 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
13:48:08 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: scInput_edited.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter
         Local applications dir : C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:48:08 Running the workflow script
         -----------------------------------------------------------------------
13:48:08 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
13:48:08 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

file: RSN1714_NORTH392_W70000.AT2 NPTS= 749 dT= 749 0.01
eventTimeSeriesObj got
eventTimeSeries got
eventFactor got


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running Simulation app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performSIMULATION\capacitySpectrum\runCMS2.py" "--filenameAIM" "AIM.json" "--filenameSAM" "SAM.json" "--filenameEVENT" "EVENT.json" "--filenameEDP" "EDP.json" "--filenameSIM" "SIM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------
13:48:10 Creating the workflow driver file
13:48:10 driver.bat
         Workflow driver file successfully created.
         -----------------------------------------------------------------------
         Gathering Workflow Inputs.
Output:

RANDOM VARIABLES: numORIG: 1 new: 1
RANDOM VARIABLES: numORIG: 0 new: 1
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in AIM.json.sc AIM.json
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in EVENT.json.sc EVENT.json


         Successfully Gathered Inputs.
         -----------------------------------------------------------------------
13:48:10 Running response simulation
         Simulation command:

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performUQ\dakota\DakotaUQ.py" "--workflowInput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter\templatedir/sc_scInput_edited.json" "--driverFile" "sc_driver" "--workflowOutput" "EDP.json" "--runType" "runningLocal"

Output:

cwd: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI\tmp.SimCenter\templatedir
EVAL CONCURRENCY: 12
NEW ORDER:
 size: 1
1 0
Running Dakota:  dakota -input dakota.in -output dakota.out -error dakota.err


         -----------------------------------------------------------------------
13:48:16 Running damage and loss assessment

=== STDERR ===
Traceback (most recent call last):
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 272, in <module>
    main(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 204, in main
    runSWhale(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py", line 121, in runSWhale
    WF.estimate_losses(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\whale\main.py", line 2704, in estimate_losses
    shutil.copy(
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\lib\shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\varun\\OneDrive - Stanford\\Desktop\\Stanford\\5. Autumn 25 Quarter\\Independent Study CEE299\\PBE_Analysis\\From_GUI\\tmp.SimCenter\\templatedir\\scInput_edited.json'

Return code: 1

In [ ]:
# import os
# import subprocess
# from pathlib import Path

# WORKDIR = Path(r"C:\\Users\\varun\\Downloads")
# JSON_INPUT_FILE = WORKDIR / "scInput.json"

# PYTHON_EXE = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\python\\python.exe")
# PBE_WORKFLOW_SCRIPT = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\sWHALE.py")
# PBE_APP_WORKFLOW = Path(r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\Workflow\\WorkflowApplications.json")

# #Add Dakota bin folder to PATH for this run
# env = os.environ.copy()
# env["PATH"] = r"C:\\Users\\varun\\Downloads\\PBE_Windows_Download\\PBE_Windows_Download\\applications\\dakota\\bin" + os.pathsep + env["PATH"]
# cmd = [
#     str(PYTHON_EXE),
#     str(PBE_WORKFLOW_SCRIPT),
#     "runningLocal",
#     str(JSON_INPUT_FILE),
#     str(PBE_APP_WORKFLOW),
# ]

# print("Running:\n", " ".join(f'"{c}"' for c in cmd))
# print("CWD:", WORKDIR)

# result = subprocess.run(
#     cmd,
#     cwd=str(WORKDIR),
#     env=env,              # important: use modified PATH
#     capture_output=True,
#     text=True,
# )

# print("=== STDOUT ===")
# print(result.stdout)
# print("=== STDERR ===")
# print(result.stderr)
# print("Return code:", result.returncode)

Running:
 "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\sWHALE.py" "runningLocal" "C:\Users\varun\Downloads\scInput.json" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json"
CWD: C:\Users\varun\Downloads
=== STDOUT ===

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-28T13:40:05
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:40:05 Started running the workflow script
         -----------------------------------------------------------------------
13:40:05 Inputs provided:
         workflow input file: C:\Users\varun\Downloads\scInput.json
         application registry file: C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
13:40:05 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
13:40:05 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: scInput.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter
         Local applications dir : C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:40:05 Running the workflow script
         -----------------------------------------------------------------------
13:40:05 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
13:40:05 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

file: RSN1714_NORTH392_W70000.AT2 NPTS= 749 dT= 749 0.01
eventTimeSeriesObj got
eventTimeSeries got
eventFactor got


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running Simulation app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performSIMULATION\capacitySpectrum\runCMS2.py" "--filenameAIM" "AIM.json" "--filenameSAM" "SAM.json" "--filenameEVENT" "EVENT.json" "--filenameEDP" "EDP.json" "--filenameSIM" "SIM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------
13:40:21 Creating the workflow driver file
13:40:21 driver.bat
         Workflow driver file successfully created.
         -----------------------------------------------------------------------
         Gathering Workflow Inputs.
Output:

RANDOM VARIABLES: numORIG: 1 new: 1
RANDOM VARIABLES: numORIG: 0 new: 1
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in AIM.json.sc AIM.json
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in EVENT.json.sc EVENT.json


         Successfully Gathered Inputs.
         -----------------------------------------------------------------------
13:40:21 Running response simulation
         Simulation command:

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performUQ\dakota\DakotaUQ.py" "--workflowInput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter\templatedir/sc_scInput.json" "--driverFile" "sc_driver" "--workflowOutput" "EDP.json" "--runType" "runningLocal"

Output:

cwd: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter\templatedir
EVAL CONCURRENCY: 12
NEW ORDER:
 size: 1
1 0
Running Dakota:  dakota -input dakota.in -output dakota.out -error dakota.err


         -----------------------------------------------------------------------
13:40:28 Running damage and loss assessment
         Damage and loss assessment command (2):

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performDL\pelicun3\pelicun3_wrapper.py" "--filenameDL" "AIM.json" "--demandFile" "response.csv" "--dirnameOutput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter"

         2025-11-28T21:40:36Z Initializing pelicun calculation.

                  The loss model does not provide loss information for the following component(s) in the asset model: [('NSA.EDU2', 'Time'), ('NSD.EDU2', 'Time')].

         2025-11-28T21:40:42Z pelicun calculation completed.

         Damage and loss assessment finished successfully.
         -----------------------------------------------------------------------
13:40:43 No performance assessment requested, performance assessment step is skipped.
         -----------------------------------------------------------------------
13:40:43 Workflow completed.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

=== STDERR ===

Return code: 0
=== STDOUT ===

sWHALE workflow

System Information:
  local time zone: Pacific Standard Time
  start time: 2025-11-28T13:40:05
  python: 3.9.11 (tags/v3.9.11:2de452f, Mar 16 2022, 14:33:45) [MSC v.1929 64 bit (AMD64)]
  numpy: 1.26.4
  pandas: 2.2.3

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:40:05 Started running the workflow script
         -----------------------------------------------------------------------
13:40:05 Inputs provided:
         workflow input file: C:\Users\varun\Downloads\scInput.json
         application registry file: C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\Workflow\WorkflowApplications.json
         run type: runningLocal
         -----------------------------------------------------------------------
WF: parType, mpiExec, numProc:  seqRUN mpiExec 8
WF: parType, mpiExec, numProc, do? numP, procID:  seqRUN mpiExec 8 False 1 0
13:40:05 Parsing application registry file
         Loading the json file...
           OK
         Loading default values...
           OK
         Collecting application data...
           OK
         Successfully parsed application registry
         -----------------------------------------------------------------------
13:40:05 Parsing workflow input file
         Loading the json file...
           OK
         The following units were specified in the GeneralInformation section:
           force: kips
           length: ft
           temperature: C
           time: sec
         Missing output type specification, using default settings.
         The following workflow defaults were overwritten:
           driverFile: driver
           edpFiles: ['EDP.json']
           filenameAIM: AIM.json
           filenameDL: AIM.json
           filenameEDP: EDP.json
           filenameEVENT: EVENT.json
           filenameSAM: SAM.json
           filenameSIM: SIM.json
           rvFiles: ['AIM.json', 'SAM.json', 'EVENT.json', 'SIM.json']
           workflowInput: scInput.json
           workflowOutput: EDP.json
         Run dir : C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter
         Local applications dir : C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download
         Remote applications dir : C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download
         Reference dir : None

         Parsing the requested list of applications...
         For Modeling
           Registering application MDOF_BuildingModel
         For EDP
           Registering application StandardEarthquakeEDP
         For Simulation
           Registering application CapacitySpectrumMethod2
         For UQ
           Registering application Dakota-UQ
         For DL
           Registering application Pelicun3

         Requested workflow:
                Event : ExistingPEER_Events
                Modeling : MDOF_BuildingModel
                EDP : StandardEarthquakeEDP
                Simulation : CapacitySpectrumMethod2
                UQ : Dakota-UQ
                DL : Pelicun3

         Successfully parsed workflow inputs
         -----------------------------------------------------------------------

Starting sWHALE workflow

--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
13:40:05 Running the workflow script
         -----------------------------------------------------------------------
13:40:05 Initializing the simulation directory

         Simulation directory successfully initialized.

         -----------------------------------------------------------------------
13:40:05 Running preprocessing step random variables

         Running Event app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEVENT\multiplePEER\MultiplePEER" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--getRV"

Output: 0

file: RSN1714_NORTH392_W70000.AT2 NPTS= 749 dT= 749 0.01
eventTimeSeriesObj got
eventTimeSeries got
eventFactor got


         -----------------------------------------------------------------------

         Running Modeling app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createSAM\mdofBuildingModel\MDOF_BuildingModel" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running EDP app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\createEDP\standardEarthquakeEDP\StandardEQEDP" "--filenameAIM" "AIM.json" "--filenameEVENT" "EVENT.json" "--filenameSAM" "SAM.json" "--filenameEDP" "EDP.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------

         Running Simulation app at preprocessing step...

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performSIMULATION\capacitySpectrum\runCMS2.py" "--filenameAIM" "AIM.json" "--filenameSAM" "SAM.json" "--filenameEVENT" "EVENT.json" "--filenameEDP" "EDP.json" "--filenameSIM" "SIM.json" "--getRV"

Output: 0



         -----------------------------------------------------------------------
13:40:21 Creating the workflow driver file
13:40:21 driver.bat
         Workflow driver file successfully created.
         -----------------------------------------------------------------------
         Gathering Workflow Inputs.
Output:

RANDOM VARIABLES: numORIG: 1 new: 1
RANDOM VARIABLES: numORIG: 0 new: 1
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in AIM.json.sc AIM.json
"C:/Users/varun/Downloads/PBE_Windows_Download/PBE_Windows_Download/applications/performUQ/templateSub/simCenterSub.exe" params.in EVENT.json.sc EVENT.json


         Successfully Gathered Inputs.
         -----------------------------------------------------------------------
13:40:21 Running response simulation
         Simulation command:

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performUQ\dakota\DakotaUQ.py" "--workflowInput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter\templatedir/sc_scInput.json" "--driverFile" "sc_driver" "--workflowOutput" "EDP.json" "--runType" "runningLocal"

Output:

cwd: C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter\templatedir
EVAL CONCURRENCY: 12
NEW ORDER:
 size: 1
1 0
Running Dakota:  dakota -input dakota.in -output dakota.out -error dakota.err


         -----------------------------------------------------------------------
13:40:28 Running damage and loss assessment
         Damage and loss assessment command (2):

"C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\python\python.exe" "C:\Users\varun\Downloads\PBE_Windows_Download\PBE_Windows_Download\applications\performDL\pelicun3\pelicun3_wrapper.py" "--filenameDL" "AIM.json" "--demandFile" "response.csv" "--dirnameOutput" "C:\Users\varun\OneDrive - Stanford\Desktop\Stanford\5. Autumn 25 Quarter\Independent Study CEE299\PBE_Analysis\From_GUI2\tmp.SimCenter"

         2025-11-28T21:40:36Z Initializing pelicun calculation.

                  The loss model does not provide loss information for the following component(s) in the asset model: [('NSA.EDU2', 'Time'), ('NSD.EDU2', 'Time')].

         2025-11-28T21:40:42Z pelicun calculation completed.

         Damage and loss assessment finished successfully.
         -----------------------------------------------------------------------
13:40:43 No performance assessment requested, performance assessment step is skipped.
         -----------------------------------------------------------------------
13:40:43 Workflow completed.
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

=== STDERR ===

Return code: 0

In [ ]:
# Convert the below run to a function that takes in the JSON input file path and runs the PBE workflow with the outputs in the corresponding building folder
# def run_pbe_workflow(json_input_file, python_exe, pbe_workflow_script, pbe_app_workflow):
#     import subprocess
#     command = [python_exe, pbe_workflow_script, "runningLocal", json_input_file, pbe_app_workflow]
#     subprocess.run(command)
# # Example usage:
# # run_pbe_workflow(JSON_INPUT_FILE, PYTHON_EXE, PBE_WORKFLOW_SCRIPT, PBE_APP_WORKFLOW)